### ISSUE TITLE
How are you supposed to use this library with promises (Mocha)?

### ISSUE THREAD

**Issue by fatuhoku** [gampleman/quick_check.js#10] opened 2016-01-14 00:14 UTC

**Comment by gampleman** [comment] 2016-01-14 10:48
Can you clarify what the problem is?

**Comment by fatuhoku** [comment] 2016-01-14 11:38
What if the function under test is actually a asynchronous function, whose implementation has been mocked out to execute synchronously?

i.e. how does quick_test work with callbacks?

Let's say you're performing a network call with Mocha.

```js
it('does async stuff', function(done) {

    asyncSquareNumberWithCallback(42)
        .then(function(value) {
             value.should.be.squareNumber;
             done();
        }).catch(function(error) {
            // Deal with the error.
        });

});
```

Instead of just testing for 42, I want to test this async function for `n` where `n in [1..100]`.

```js
it('does async stuff', function(done) {

    qc.forAll(qc.array,  function(n) {
        asyncSquareNumberWithCallback(n)
            .then(function(value) {
                 value.should.be.squareNumber;
                 done();   // !!!!!!!! passes test on first go!
            }).catch(function(error) {
                // Deal with the error.
            });
    });

});
```

There needs to be a way of forcing the promise to execute asynchronously, and getting `qc.forAll` to join on all the promises. See https://justinbellamy.com/testing-async-code-with-mocha/

**Comment by gampleman** [comment] 2016-01-14 13:53
This library doesn't really solve this problem since most testing frameworks already answer the problem in various ways. 

You have I think two good options. The proper one is to mock out the side effect that causes the test to run asynchronously. However in practical programming that can be quite difficult at times. The other thing you can try, is simply changing your above code to this:

```javascrip

 qc.forAll(qc.array,  function(n) {
     it('does async stuff with ' + n, function(done) {
        asyncSquareNumberWithCallback(n)
            .then(function(value) {
                 value.should.be.squareNumber;
                 done();   // !!!!!!!! passes test on first go!
            }).catch(function(error) {
                // Deal with the error.
            });
    });
});
```

**Comment by gampleman** [comment] 2016-01-14 13:57
I suppose another option would be something like this:

it('does async stuff', function(done) {
   var results = [];
    qc.forAll(qc.array,  function(n) {
        results.push(asyncSquareNumberWithCallback(n));
    });
   Promise.all(results) .then(function(values) {
     values.map(function(value) {
                 value.should.be.squareNumber;
     });
     done();
    }).catch(function(error) {
                // Deal with the error.
    });
});

**Comment by gampleman** [comment] 2016-01-14 14:05
Closing in favor of the support discussion on the docs site: https://quickcheckjs.readme.io/v0.6.0/discuss/5696e3f359a6692d003fad3e

**Closed by gampleman** 2016-01-14 14:05 UTC
Labels: question
